name:  Auto Scan
on:
  push:
    branches:
    - main
# on:
#   schedule:
#     - cron: 0/15 * * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9' 
    - run: |
        pip install lxml
        python main.py "${{ secrets.U2_URL }}" "${{ secrets.U2_COOKIE }}" "${{ secrets.TTG_URL }}" "${{ secrets.TTG_COOKIE }}"
        # python main.py "${{ secrets.U2_URL }}" "${{ secrets.U2_COOKIE }}" "${{ secrets.TTG_URL }}" "${{ secrets.TTG_COOKIE }}" "${{ secrets.S }}" "${{ secrets.R }}" "${{ secrets.PASSWD }}"
    
